### PR TITLE
Removed DIRECTORY_SEPARATOR in AI1EC_TWIG_CACHE_PATH 

### PR DESCRIPTION
**Pull request by robysan83ct**
it added a double slash in path

### CODE REVIEW

**Comment by uchu** [comment]
@robysan83ct , thanks, merged.

**Comment by robysan83ct** [comment]
thanks @uchu. I Translated the plugin Italian on Wordpress.org, but I Translated The plug-in Italian , but translations are still " waiting". have I to add theme, here?

**Comment by uchu** [comment]
@robysan83ct , we'll take a look why they are "waiting" and approve them if we can.
No, it doesn't need to be added here.
Thanks a lot!

**Comment by robysan83ct** [comment]
Ok thanks to you

**Comment by uchu** [comment]
@robysan83ct , We currently can't see any Italian translation pending approval. Please, raise a question about the translation you made in the Wordpress forums of our plugin. It will be more easy to resolve it there. Thanks!

**Comment by robysan83ct** [comment]
@uchu I translated plugin in directory Deveolpment (trunk)
https://translate.wordpress.org/projects/wp-plugins/all-in-one-event-calendar/dev/it/default

**Comment by calvin-yeh** [comment]
Hi @robysan83ct !

The translations should be made in the https:/translate.time.ly project, as we will export these files when releasing new versions. It was an error to commit these files to this repo, so I've just removed them.

**Comment by robysan83ct** [comment]
Hi, @calvin-yeh!

I not able to translate in the https://translate.time.ly project. Because i haven't a login name and password.

**Pull request merged**
