### PR TITLE
EDIT AI1EC_TWIG_CACHE_PATH

### PR DESCRIPTION
**Pull request by robysan83ct**
Removed DIRECTORY_SEPARATO from EDIT AI1EC_TWIG_CACHE_PATH, because it add add a second slash in path before twig directory

### CODE REVIEW

**Comment by uchu** [comment]
@robysan83ct , thanks for contributing, but I don't see any commits from you here. Could you please kindly create a new fresh PR? Closing this one.

**Comment by robysan83ct** [comment]
I tried to do a commit , but it returns a permissions error. How can I do?

I also made ​​the translation of the plugin on wordpress , but the terms
are waiting.

Roberto Caradonna
Il 17/Feb/2016 16:44, "Pavel Burylichev" <notifications@github.com> ha
scritto:

**Comment by alberto-aglobalway** [comment]
Hi Roberto,

Pls see guidelines here:
https://guides.github.com/activities/contributing-to-open-source/

Think you're missing forking this repo so you can make the changes and then submitting a PR to this repo so it can be reviewed by the maintainers and merged if all is good.

Thanks for contributing!

Cheers,
Alberto

**Comment by robysan83ct** [comment]
Sorry, but I'm not able to submitting a PR. I'm not able to test a plugin
with my Eclipse configuration

2016-02-17 23:57 GMT+01:00 Alberto Mota <notifications@github.com>:

> Hi Roberto,
>
> Pls see guidelines here:
> https://guides.github.com/activities/contributing-to-open-source/
>
> Think you're missing forking this repo so you can make the changes and
> then submitting a PR to this repo so it can be reviewed by the maintainers
> and merged if all is good.
>
> Thanks for contributing!
>
> Cheers,
> Alberto
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thenly/all-in-one-event-calendar/pull/934#issuecomment-185447922>
> .
>



-- 
Roberto Caradonna

**Pull request closed without merging**
